
import 'bootstrap-icons/font/bootstrap-icons.css';
import './assets/style/tuanworksstyle.scss'
import BackgroundGrid from './components/bgGrid'
import Footer from './components/footer'
import { Navbar } from './components/navbar'
import Contact from './contact/contact'

export const metadata = {
  title: 'Tuan works',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-bs-theme="dark">
      <body className='vh-100'>
        <div className='container-fluid h-100 d-flex flex-column'>
          <BackgroundGrid />
          <header className='row z-3'>
            <Navbar />
          </header>
          <main className='row mt-5'>
            <div className='container-fluid mt-5'>
              {children}
            </div>
          </main>
          <div className='row py-5'>
            <Contact />
          </div>
          <footer className='mt-auto row py-5 border-top border-primary border-opacity-10'>
            <Footer />
          </footer>
        </div>
      </body>
    </html>
  )
}
